mod math;
pub use self::math::find_candidates;
pub use self::math::best_max_for_sieve;
pub use self::math::sieve_page;
pub use self::math::best_partitioning;
pub use self::math::init_primes;
mod types;
pub use self::types::Partition;
mod errors;
pub use self::errors::MathError;
